# Generated by Django 4.2 on 2023-04-05 10:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_seats', models.IntegerField(default=1)),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='master.airport')),
                ('flight_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flightname', to='master.aircraft')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='master.airport')),
            ],
        ),
    ]
